server:
  port: ${port.account}

accountServiceUrl: http://${host.account}:${port.account}

spring:
    data:
        mongodb:
            host: ${host.mongodb}
            port: ${port.mongodb}
            database: accountdb
zooKeeper:
    hosts: ${zooKeeperHosts}
    project: ${projectName}
    service: ${service.account}
    port: ${port.account}
