server:
  port: 6006
  tomcat:
    accesslog:
      directory: /data/logs/zjhlearn-ui-web/access # Directory in which log files are created. Can be relative to the tomcat base dir or absolute.
      enabled: true # Enable access log.
      pattern: "%h %A:%p %l %u %t \"%r\" %s %b %D %{User-Agent}i"

spring:
  mobile:
    devicedelegatingviewresolver:
      enabled: true
      normal-prefix: pc/
      tablet-prefix: pc/

interceptorPathPatterns:
  authToken: ["/goods/arrivalNotice/**","/account/**","/order/**"]

cdn:
  path:
    image: /image
    style: /css
    scripts: /js

urls:
  indexUrl: //dev.jiahao.com:6006
  acountServiceApiUrl: http://127.0.0.1:7001 #对外acount api接口地址
  loginUrl: ${urls.acountServiceApiUrl}/api/account/login
  payUrl: http://store.jeep.com.cn/shoppaytest/payment/plugin_submit.jhtml #支付跳转地址
  payWechatUrl: http://store.jeep.com.cn/shoptest/wechat/auth #微信跳转地址